config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  #get 'city', to: 'static_pages#city'
  #get 'welcome(/:first_name)', to: 'pages#welcome', as: 'welcome'
  resources :gossips do
    resources :users, only:[:show, :new, :create]
    resources :likes, only:[:new, :create, :destroy]
  end
  resources :cities, only:[:show]
  resources :users
  resources :sessions,only:[:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  belongs_to :user, optional: true
  has_many :tag_gossips
  has_many :tags, through: :tag_gossips
  has_many :comments
  
  validates :title, presence: true, length: {in: 3..50}
  validates :content, presence: true
  has_many :likes, dependent: :destroy
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: %i[ show edit update destroy ]
  before_action :authenticate_user, only: [:new, :create, :show]
  
  # GET :: Gossip
  def index
    @gossips = Gossip.all
  end

   # GET :: /gossips/new
  def new
    @gossip = Gossip.new
  end

  # POST :: /gossips
  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.user = current_user
      if @gossip.save && @gossip.user = User.find_by(id: session[:user_id])
        flash[:notice] = 'The gossip were successfully created'
        redirect_to gossips_url
      else
        flash[:notice] = 'The gossip can not be created, it is not completed'
        redirect_to gossip_path(params[:id])
      end
  end

  # GET /gossips/1 or /gossips/1.json
  def show
    @comments = Comment.all
    @user = User.all
    current_user = @gossip.user
  end

  # GET /gossips/1/edit
  def edit
    @gossip = Gossip.find(params[:id])
  end

  # PATCH/PUT /gossips/1 or /gossips/1.json
  def update
    if @gossip.user_id == current_user.id
      if @gossip.update(gossip_params) 
        flash[:notice] = 'The gossip were successfully updated'
        redirect_to gossips_url
      else
        flash[:notice] = 'The gossip can not be updated, you are not the author of this gossip'
        redirect_to gossip_path(params[:id])
      end
    else
      flash[:notice] = 'The gossip can not be updated, you are not the author of this comment'
      redirect_to gossip_path(params[:id])
    end
  end

  # DELETE :: /gossips/
  def destroy
    if @gossip.user_id == current_user.id
      if @gossip.destroy 
        flash[:notice] = 'The gossip were successfully deleted'
        redirect_to gossips_url
      else
        flash[:notice] = 'The gossip can not be deleted, you are not the author of this gossip'
        redirect_to gossips_url
      end
    else
      flash[:notice] = 'The gossip can not be deleted, you are not the author of this comment'
      redirect_to gossips_url
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gossip_params
      params.require(:gossip).permit(:title, :content, :user_id)
    end

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
      <% gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


    
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gossips</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.title %></td>
        <td><%= gossip.content %></td>
        <td><%= link_to 'Show', gossip %></td>
        <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
        <td><%= gossip.likes.count %> <%= (gossip.likes.count) == 1 ? 'Like' : 'Likes'%></td>
        <td><%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>
<br>
<% if current_user%>
  <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
  <% else %>
  <%= link_to     "Connexion", new_session_path %>


<% end %>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gossip.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<strong>Le gossiper</strong>
  <% gossiper = User.find(@gossip.user_id)  %>
  <%= link_to gossiper.first_name, user_path(gossiper.id) %>

  <br><br>

<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

<p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', gossip_like_path(@gossip.id, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', gossip_likes_path(@gossip.id), method: :post %>
<% end %>

<p>
<br><br>
  <strong>Commentaires</strong>
  <br>
  <p>Ecrire un nouveau commentaire</p>
  <%= form_tag gossip_comments_path(@gossip), :method => :post do%>
    <div class="field">
      <%= label_tag :content%>
      <%= text_area_tag :content %>
    </div>
    
    <div class="actions">
      <%= submit_tag "Create Comment" %>
    </div>
  
  <% end %>
  
  <br>
  <% comments = Comment.where(gossip_id: params[:id]) %>
  <br>
    <% comments.each do |comment| %>
      <% user_comment = comment.user %>
      <%= user_comment.first_name %>
      <br>
      <%= comment.content %>
      <br><br>
      <% end %>

         
</p>